/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marthahamlin
 */
public class BestiaryGUI extends javax.swing.JFrame {

    /**
     * Creates new form BestiaryGUI
     */
    public BestiaryGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModeToggle = new javax.swing.ButtonGroup();
        MonsterEdit = new javax.swing.JDialog();
        MonsterEdit_TopPane = new javax.swing.JPanel();
        MonsterEdit_HeaderInfo = new javax.swing.JPanel();
        MonsterEdit_Row1 = new javax.swing.JPanel();
        MonsterEdit_NamePanel = new javax.swing.JPanel();
        MonsterEdit_NameTitle = new javax.swing.JLabel();
        MonsterEdit_NameField = new javax.swing.JTextField();
        MonsterEdit_MonsterTagsButton = new javax.swing.JButton();
        MonsterEdit_Row2 = new javax.swing.JPanel();
        MonsterEdit_HPValue = new javax.swing.JSpinner();
        MonsterEdit_HPLabel = new javax.swing.JLabel();
        MonsterEdit_ArmorValue = new javax.swing.JSpinner();
        MonsterEdit_ArmorLabel = new javax.swing.JLabel();
        MonsterEdit_Row3 = new javax.swing.JPanel();
        MonsterEdit_AttackNameLabel = new javax.swing.JLabel();
        MonsterEdit_AttackNameField = new javax.swing.JTextField();
        MonsterEdit_Rolls = new javax.swing.JComboBox();
        MonsterEdit_Dice = new javax.swing.JComboBox();
        MonsterEdit_AttackMod = new javax.swing.JSpinner();
        MonsterEdit_AttackTags = new javax.swing.JButton();
        MonsterEdit_Row4 = new javax.swing.JPanel();
        MonsterEdit_SpecialQualitiesLabel = new javax.swing.JLabel();
        MonsterEdit_SpecialQualitiesField = new javax.swing.JTextField();
        MonsterEdit_Description = new javax.swing.JPanel();
        MonsterEdit_DescriptionLabel = new javax.swing.JLabel();
        MonsterEdit_DescriptionScrollPane = new javax.swing.JScrollPane();
        MonsterEdit_DescriptionPane = new javax.swing.JTextArea();
        MonsterEdit_InstinctBox = new javax.swing.JPanel();
        MonsterEdit_InstinctLabel = new javax.swing.JLabel();
        MonsterEdit_InstinctField = new javax.swing.JTextField();
        MonsterEdit_filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        MonsterEdit_filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        MonsterEdit_Moves = new javax.swing.JPanel();
        MonsterEdit_MovesControlsBox = new javax.swing.JPanel();
        MonsterEdit_NewMoveField = new javax.swing.JTextField();
        MonsterEdit_RemoveButton = new javax.swing.JButton();
        MonsterEdit_AddMoveButton = new javax.swing.JButton();
        MonsterEdit_MovesLabel = new javax.swing.JLabel();
        MonsterEdit_MovesScrollPane = new javax.swing.JScrollPane();
        MonsterEdit_MovesList = new javax.swing.JList();
        MonsterEdit_EndPane = new javax.swing.JPanel();
        MonsterEdit_SaveButton = new javax.swing.JButton();
        MonsterEdit_CancelButton = new javax.swing.JButton();
        MonsterEdit_filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        MonsterEdit_filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        MonsterEdit_filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        MonsterEdit_filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        MonsterEdit_filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        MonsterEdit_filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        MonsterSurvey = new javax.swing.JDialog();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jBtnSurveyBack = new javax.swing.JButton();
        jBtnSurveyNext = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel44 = new javax.swing.JPanel();
        jBtnSurveyCancel = new javax.swing.JButton();
        jPanel45 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jBtnSurveyBack = new javax.swing.JButton();
        jBtnSurveyNext = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel37 = new javax.swing.JPanel();
        jBtnSurveyCancel = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();
        MonsterTagsWindow = new javax.swing.JDialog();
        mTagWindow_GridBox = new javax.swing.JPanel();
        mTagWindow_MonsterTagsTitle = new javax.swing.JLabel();
        mTagWindow_OrgTagsTitle = new javax.swing.JLabel();
        mTagWindow_Magical = new javax.swing.JCheckBox();
        mTagWindow_Horde = new javax.swing.JRadioButton();
        mTagWindow_Devious = new javax.swing.JCheckBox();
        mTagWindow_Group = new javax.swing.JRadioButton();
        mTagWindow_Amorphous = new javax.swing.JCheckBox();
        mTagWindow_Solitary = new javax.swing.JRadioButton();
        mTagWindow_Organized = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20));
        mTagWindow_Intelligent = new javax.swing.JCheckBox();
        mTagWindow_SizeTagsTitle = new javax.swing.JLabel();
        mTagWindow_Hoarder = new javax.swing.JCheckBox();
        mTagWindow_Tiny = new javax.swing.JRadioButton();
        mTagWindow_Stealthy = new javax.swing.JCheckBox();
        mTagWindow_Small = new javax.swing.JRadioButton();
        mTagWindow_Terrifying = new javax.swing.JCheckBox();
        mTagWindow_Normal = new javax.swing.JRadioButton();
        mTagWindow_Cautious = new javax.swing.JCheckBox();
        mTagWindow_Large = new javax.swing.JRadioButton();
        mTagWindow_Construct = new javax.swing.JCheckBox();
        mTagWindow_Huge = new javax.swing.JRadioButton();
        mTagWindow_Planar = new javax.swing.JCheckBox();
        mTagWindow_ButtonBox = new javax.swing.JPanel();
        mTagWindow_cancelButton = new javax.swing.JButton();
        mTagWindow_saveButton = new javax.swing.JButton();
        AttackTagsWindow = new javax.swing.JDialog();
        aTagsWindow_Title = new javax.swing.JLabel();
        aTagsWindow_GridBox = new javax.swing.JPanel();
        aTagsWindow_AmmoBox = new javax.swing.JPanel();
        aTagsWindow_AmmoCheck = new javax.swing.JCheckBox();
        aTagsWindow_AmmoSpin = new javax.swing.JSpinner();
        aTagsWindow_AmmoLabel = new javax.swing.JLabel();
        aTagsWindow_StunCheck = new javax.swing.JCheckBox();
        aTagsWindow_ForcefulCheck = new javax.swing.JCheckBox();
        aTagsWindow_ThrownCheck = new javax.swing.JCheckBox();
        aTagsWindow_IgnoresArmorCheck = new javax.swing.JCheckBox();
        aTagsWindow_HandCheck = new javax.swing.JCheckBox();
        aTagsWindow_MessyCheck = new javax.swing.JCheckBox();
        aTagsWindow_CloseCheck = new javax.swing.JCheckBox();
        aTagsWindow_PiercingBox = new javax.swing.JPanel();
        aTagsWindow_PiercingCheck = new javax.swing.JCheckBox();
        aTagsWindow_PiercingSpin = new javax.swing.JSpinner();
        aTagsWindow_PiercingLabel = new javax.swing.JLabel();
        aTagsWindow_ReachCheck = new javax.swing.JCheckBox();
        aTagsWindow_PreciseCheck = new javax.swing.JCheckBox();
        aTagsWindow_NearCheck = new javax.swing.JCheckBox();
        aTagsWindow_ReloadCheck = new javax.swing.JCheckBox();
        aTagsWindow_FarCheck = new javax.swing.JCheckBox();
        aTagsWindow_ButtonBox = new javax.swing.JPanel();
        aTagsWindow_CancelButton = new javax.swing.JButton();
        aTagsWindow_SaveButton = new javax.swing.JButton();
        OrganizationTagsGroup = new javax.swing.ButtonGroup();
        SizeTagsGroup = new javax.swing.ButtonGroup();
        myBestiaryOrgTags = new javax.swing.ButtonGroup();
        myBestiarySizeTags = new javax.swing.ButtonGroup();
        ControlBar = new javax.swing.JPanel();
        controlbar_MainLabel = new javax.swing.JLabel();
        ModeButtons = new javax.swing.JPanel();
        headerFiller = new javax.swing.Box.Filler(new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20), new java.awt.Dimension(20, 20));
        controlbar_MyBestiaryButton = new javax.swing.JToggleButton();
        controlbar_NewMonsterButton = new javax.swing.JToggleButton();
        controlbar_CodexButton = new javax.swing.JToggleButton();
        ModeScreens = new javax.swing.JPanel();
        BestiaryPage = new javax.swing.JPanel();
        bestiarypage_left = new javax.swing.JPanel();
        bestiarypage_mainscroll = new javax.swing.JScrollPane();
        bestiarypage_mainScrollPane = new javax.swing.JPanel();
        bestiarypage_card1 = new LargeMonsterCard();
        bestiarypage_card2 = new LargeMonsterCard();
        bestiarypage_card3 = new LargeMonsterCard();
        bestiarypage_card4 = new LargeMonsterCard();
        bestiarypage_card5 = new LargeMonsterCard();
        bestiarypage_right = new javax.swing.JPanel();
        bestiarypage_tagBoxes = new javax.swing.JPanel();
        bestiarypage_collectionTagsPane = new javax.swing.JPanel();
        bestiarypage_CollectionsLabel = new javax.swing.JLabel();
        bestiarypage_filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        bestiarypage_filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        bestiarypage_collectionsScrollPane = new javax.swing.JScrollPane();
        bestiarypage_CollectionsPane = new javax.swing.JPanel();
        bestiarypage_collectionsGridBox = new javax.swing.JPanel();
        bestiarypage_dummyCheck = new javax.swing.JCheckBox();
        bestiarypage_dummyCheck2 = new javax.swing.JCheckBox();
        bestiarypage_filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        bestiarypage_collectionsButtonBox = new javax.swing.JPanel();
        bestiarypage_collectionsClearSelectionButton = new javax.swing.JButton();
        bestiarypage_monsterTagsPane = new javax.swing.JPanel();
        bestiarypage_monsterTagsTitle = new javax.swing.JLabel();
        bestiarypage_filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        bestiarypage_filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        bestiarypage_monsterTagsScrollPane = new javax.swing.JScrollPane();
        bestiarypage_monsterTagPaneMid = new javax.swing.JPanel();
        bestiarypage_filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        bestiarypage_monsterTagsGridBox = new javax.swing.JPanel();
        bestiarypage_monsterTagsMonsterLabel = new javax.swing.JLabel();
        bestiarypage_tag_Magical = new javax.swing.JCheckBox();
        bestiarypage_tag__Devious = new javax.swing.JCheckBox();
        bestiarypage_tag_Amorphous = new javax.swing.JCheckBox();
        bestiarypage_tag_Organized = new javax.swing.JCheckBox();
        bestiarypage_tag_Intelligent = new javax.swing.JCheckBox();
        bestiarypage_tag_Hoarder = new javax.swing.JCheckBox();
        bestiarypage_tag_Stealthy = new javax.swing.JCheckBox();
        bestiarypage_tag_Terrifying = new javax.swing.JCheckBox();
        bestiarypage_tag_Cautious = new javax.swing.JCheckBox();
        bestiarypage_tag_Construct = new javax.swing.JCheckBox();
        bestiarypage_tag_Planar = new javax.swing.JCheckBox();
        bestiarypage_monsterTagsOrgLabel = new javax.swing.JLabel();
        bestiarypage_tag_Horde = new javax.swing.JCheckBox();
        bestiarypage_tag_Group = new javax.swing.JCheckBox();
        bestiarypage_tag_Solitary = new javax.swing.JCheckBox();
        bestiarypage_monsterTagsSizeLabel = new javax.swing.JLabel();
        bestiarypage_tag_Tiny = new javax.swing.JCheckBox();
        bestiarypage_tag_Small = new javax.swing.JCheckBox();
        bestiarypage_tag_Normal = new javax.swing.JCheckBox();
        bestiarypage_tag_Large = new javax.swing.JCheckBox();
        bestiarypage_tag_Huge = new javax.swing.JCheckBox();
        bestiarypage_monsterTagButtonBox = new javax.swing.JPanel();
        bestiarypage_monsterTagClearSelectionsButton = new javax.swing.JButton();
        bestiarypage_filterPane = new javax.swing.JPanel();
        bestiarypage_filterButton = new javax.swing.JButton();
        MonsterFocus = new javax.swing.JPanel();
        monsterFocus_Sidebar = new javax.swing.JPanel();
        monsterFocus_UploadBox = new javax.swing.JPanel();
        monsterFocus_UploadButton = new javax.swing.JButton();
        monsterFocus_filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        monsterFocus_filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        monsterFocus_filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        monsterFocus_filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        monsterFocus_currentCollectionsPane = new javax.swing.JPanel();
        monsterFocus_currentCollectionsTitle = new javax.swing.JLabel();
        monsterFocus_currentCollectionsEditPane = new javax.swing.JPanel();
        monsterFocus_currentCollectionsEditButton = new javax.swing.JButton();
        monsterFocus_currentCollectionsScrollPane = new javax.swing.JScrollPane();
        monsterFocus_currentCollectionsList = new javax.swing.JList();
        monsterFocus_filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        monsterFocus_filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        monsterFocus_GMNotePane = new javax.swing.JPanel();
        monsterFocus_GMNotesTitle = new javax.swing.JLabel();
        monsterFocus_GMNotesScrollPane = new javax.swing.JScrollPane();
        monsterFocus_GMNotesTextArea = new javax.swing.JTextArea();
        monsterFocus_filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        monsterFocus_filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        monsterFocus_GMNotesButtonBox = new javax.swing.JPanel();
        monsterFocus_GMNotesEditButton = new javax.swing.JButton();
        monsterFocus_MonsterCard = new LargeMonsterCard();
        monsterFocus_BackButtonBox = new javax.swing.JPanel();
        monsterFocus_backButton = new javax.swing.JButton();
        CodexPage = new javax.swing.JPanel();
        CodexPage_MainScrollPanel = new javax.swing.JScrollPane();
        CodexPage_MainPanel = new javax.swing.JPanel();
        CodexPage_PopularMonstersTopPanel = new javax.swing.JPanel();
        CodexPage_filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        CodexPage_filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        CodexPage_PopularMonstersCards = new javax.swing.JPanel();
        CodexPage_PopularCard1 = new MiniMonsterCard();
        CodexPage_PopularCard2 = new MiniMonsterCard();
        CodexPage_PopularCard3 = new MiniMonsterCard();
        CodexPage_PopularCard4 = new MiniMonsterCard();
        CodexPage_PopularCard5 = new MiniMonsterCard();
        CodexPage_PopularMonsterTitle = new javax.swing.JLabel();
        CodexPage_RecentMonstersTopPane = new javax.swing.JPanel();
        CodexPage_filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        CodexPage_filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        CodexPage_RecentMonstersCards = new javax.swing.JPanel();
        CodexPage_RecentCard1 = new MiniMonsterCard();
        CodexPage_RecentCard2 = new MiniMonsterCard();
        CodexPage_RecentCard3 = new MiniMonsterCard();
        CodexPage_RecentCard4 = new MiniMonsterCard();
        CodexPage_RecentCard5 = new MiniMonsterCard();
        CodexPage_RecentMonstersTitle = new javax.swing.JLabel();

        MonsterEdit.setAlwaysOnTop(true);
        MonsterEdit.setResizable(false);
        MonsterEdit.setSize(new java.awt.Dimension(700, 500));

        MonsterEdit_TopPane.setLayout(new java.awt.BorderLayout());

        MonsterEdit_HeaderInfo.setLayout(new java.awt.GridLayout(4, 0));

        MonsterEdit_Row1.setLayout(new java.awt.BorderLayout());

        MonsterEdit_NameTitle.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        MonsterEdit_NameTitle.setText("Name:");
        MonsterEdit_NamePanel.add(MonsterEdit_NameTitle);

        MonsterEdit_NameField.setPreferredSize(new java.awt.Dimension(300, 28));
        MonsterEdit_NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonsterEdit_NameFieldActionPerformed(evt);
            }
        });
        MonsterEdit_NamePanel.add(MonsterEdit_NameField);

        MonsterEdit_Row1.add(MonsterEdit_NamePanel, java.awt.BorderLayout.WEST);

        MonsterEdit_MonsterTagsButton.setText("Monster Tags");
        MonsterEdit_Row1.add(MonsterEdit_MonsterTagsButton, java.awt.BorderLayout.EAST);

        MonsterEdit_HeaderInfo.add(MonsterEdit_Row1);

        MonsterEdit_Row2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        MonsterEdit_HPValue.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        MonsterEdit_Row2.add(MonsterEdit_HPValue);

        MonsterEdit_HPLabel.setText("HP      ");
        MonsterEdit_Row2.add(MonsterEdit_HPLabel);

        MonsterEdit_ArmorValue.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        MonsterEdit_Row2.add(MonsterEdit_ArmorValue);

        MonsterEdit_ArmorLabel.setText("Armor");
        MonsterEdit_Row2.add(MonsterEdit_ArmorLabel);

        MonsterEdit_HeaderInfo.add(MonsterEdit_Row2);

        MonsterEdit_Row3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        MonsterEdit_AttackNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        MonsterEdit_AttackNameLabel.setText("Attack Name:");
        MonsterEdit_Row3.add(MonsterEdit_AttackNameLabel);

        MonsterEdit_AttackNameField.setPreferredSize(new java.awt.Dimension(175, 28));
        MonsterEdit_AttackNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonsterEdit_AttackNameFieldActionPerformed(evt);
            }
        });
        MonsterEdit_Row3.add(MonsterEdit_AttackNameField);

        MonsterEdit_Rolls.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Best of 2", "Worst of 2" }));
        MonsterEdit_Row3.add(MonsterEdit_Rolls);

        MonsterEdit_Dice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "d4", "d6", "d8", "d10", "d12", "d20" }));
        MonsterEdit_Row3.add(MonsterEdit_Dice);

        MonsterEdit_AttackMod.setModel(new javax.swing.SpinnerNumberModel(0, -20, 20, 1));
        MonsterEdit_AttackMod.setVerifyInputWhenFocusTarget(false);
        MonsterEdit_Row3.add(MonsterEdit_AttackMod);

        MonsterEdit_AttackTags.setText("Attack Tags");
        MonsterEdit_Row3.add(MonsterEdit_AttackTags);

        MonsterEdit_HeaderInfo.add(MonsterEdit_Row3);

        MonsterEdit_Row4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        MonsterEdit_SpecialQualitiesLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        MonsterEdit_SpecialQualitiesLabel.setText("Special Qualities:");
        MonsterEdit_Row4.add(MonsterEdit_SpecialQualitiesLabel);

        MonsterEdit_SpecialQualitiesField.setPreferredSize(new java.awt.Dimension(400, 28));
        MonsterEdit_Row4.add(MonsterEdit_SpecialQualitiesField);

        MonsterEdit_HeaderInfo.add(MonsterEdit_Row4);

        MonsterEdit_TopPane.add(MonsterEdit_HeaderInfo, java.awt.BorderLayout.NORTH);

        MonsterEdit_Description.setLayout(new java.awt.BorderLayout());

        MonsterEdit_DescriptionLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        MonsterEdit_DescriptionLabel.setText(" Description:");
        MonsterEdit_DescriptionLabel.setMaximumSize(new java.awt.Dimension(86, 20));
        MonsterEdit_DescriptionLabel.setPreferredSize(new java.awt.Dimension(86, 22));
        MonsterEdit_Description.add(MonsterEdit_DescriptionLabel, java.awt.BorderLayout.PAGE_START);

        MonsterEdit_DescriptionPane.setColumns(20);
        MonsterEdit_DescriptionPane.setLineWrap(true);
        MonsterEdit_DescriptionPane.setRows(5);
        MonsterEdit_DescriptionScrollPane.setViewportView(MonsterEdit_DescriptionPane);

        MonsterEdit_Description.add(MonsterEdit_DescriptionScrollPane, java.awt.BorderLayout.CENTER);

        MonsterEdit_InstinctBox.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        MonsterEdit_InstinctLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        MonsterEdit_InstinctLabel.setText("Instinct:");
        MonsterEdit_InstinctBox.add(MonsterEdit_InstinctLabel);

        MonsterEdit_InstinctField.setPreferredSize(new java.awt.Dimension(300, 28));
        MonsterEdit_InstinctField.setSize(new java.awt.Dimension(200, 28));
        MonsterEdit_InstinctBox.add(MonsterEdit_InstinctField);

        MonsterEdit_Description.add(MonsterEdit_InstinctBox, java.awt.BorderLayout.SOUTH);
        MonsterEdit_Description.add(MonsterEdit_filler1, java.awt.BorderLayout.WEST);
        MonsterEdit_Description.add(MonsterEdit_filler2, java.awt.BorderLayout.EAST);

        MonsterEdit_TopPane.add(MonsterEdit_Description, java.awt.BorderLayout.CENTER);

        MonsterEdit_Moves.setLayout(new java.awt.BorderLayout());

        MonsterEdit_MovesControlsBox.setLayout(new java.awt.BorderLayout());

        MonsterEdit_NewMoveField.setText("Move");
        MonsterEdit_NewMoveField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonsterEdit_NewMoveFieldActionPerformed(evt);
            }
        });
        MonsterEdit_MovesControlsBox.add(MonsterEdit_NewMoveField, java.awt.BorderLayout.CENTER);

        MonsterEdit_RemoveButton.setText("Remove");
        MonsterEdit_MovesControlsBox.add(MonsterEdit_RemoveButton, java.awt.BorderLayout.LINE_START);

        MonsterEdit_AddMoveButton.setText("Add Move");
        MonsterEdit_MovesControlsBox.add(MonsterEdit_AddMoveButton, java.awt.BorderLayout.LINE_END);

        MonsterEdit_MovesLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        MonsterEdit_MovesLabel.setText(" Moves");
        MonsterEdit_MovesControlsBox.add(MonsterEdit_MovesLabel, java.awt.BorderLayout.PAGE_START);

        MonsterEdit_Moves.add(MonsterEdit_MovesControlsBox, java.awt.BorderLayout.NORTH);

        MonsterEdit_MovesScrollPane.setPreferredSize(new java.awt.Dimension(100, 75));

        MonsterEdit_MovesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        MonsterEdit_MovesScrollPane.setViewportView(MonsterEdit_MovesList);

        MonsterEdit_Moves.add(MonsterEdit_MovesScrollPane, java.awt.BorderLayout.CENTER);

        MonsterEdit_EndPane.setLayout(new java.awt.BorderLayout());

        MonsterEdit_SaveButton.setText("Save");
        MonsterEdit_EndPane.add(MonsterEdit_SaveButton, java.awt.BorderLayout.EAST);

        MonsterEdit_CancelButton.setText("Cancel");
        MonsterEdit_EndPane.add(MonsterEdit_CancelButton, java.awt.BorderLayout.WEST);

        MonsterEdit_Moves.add(MonsterEdit_EndPane, java.awt.BorderLayout.SOUTH);
        MonsterEdit_Moves.add(MonsterEdit_filler6, java.awt.BorderLayout.WEST);
        MonsterEdit_Moves.add(MonsterEdit_filler7, java.awt.BorderLayout.EAST);

        MonsterEdit_TopPane.add(MonsterEdit_Moves, java.awt.BorderLayout.SOUTH);

        MonsterEdit.getContentPane().add(MonsterEdit_TopPane, java.awt.BorderLayout.CENTER);
        MonsterEdit.getContentPane().add(MonsterEdit_filler8, java.awt.BorderLayout.WEST);
        MonsterEdit.getContentPane().add(MonsterEdit_filler3, java.awt.BorderLayout.EAST);
        MonsterEdit.getContentPane().add(MonsterEdit_filler4, java.awt.BorderLayout.NORTH);
        MonsterEdit.getContentPane().add(MonsterEdit_filler5, java.awt.BorderLayout.SOUTH);

        jPanel42.setLayout(new java.awt.BorderLayout());

        jBtnSurveyBack.setText("Back");
        jBtnSurveyBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSurveyBackActionPerformed(evt);
            }
        });
        jPanel43.add(jBtnSurveyBack);

        jBtnSurveyNext.setText("Next");
        jBtnSurveyNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSurveyNextActionPerformed(evt);
            }
        });
        jPanel43.add(jBtnSurveyNext);

        jPanel42.add(jPanel43, java.awt.BorderLayout.EAST);
        jPanel42.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        jBtnSurveyCancel.setText("Cancel");
        jPanel44.add(jBtnSurveyCancel);

        jPanel42.add(jPanel44, java.awt.BorderLayout.LINE_START);

        MonsterSurvey.getContentPane().add(jPanel42, java.awt.BorderLayout.PAGE_END);

        jPanel45.setLayout(new java.awt.CardLayout());
        MonsterSurvey.getContentPane().add(jPanel45, java.awt.BorderLayout.CENTER);

        jPanel34.setLayout(new java.awt.BorderLayout());

        jBtnSurveyBack.setText("Back");
        jBtnSurveyBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSurveyBackActionPerformed(evt);
            }
        });
        jPanel36.add(jBtnSurveyBack);

        jBtnSurveyNext.setText("Next");
        jBtnSurveyNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSurveyNextActionPerformed(evt);
            }
        });
        jPanel36.add(jBtnSurveyNext);

        jPanel34.add(jPanel36, java.awt.BorderLayout.EAST);
        jPanel34.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        jBtnSurveyCancel.setText("Cancel");
        jPanel37.add(jBtnSurveyCancel);

        jPanel34.add(jPanel37, java.awt.BorderLayout.LINE_START);

        MonsterSurvey.getContentPane().add(jPanel34, java.awt.BorderLayout.PAGE_END);

        jPanel35.setLayout(new java.awt.CardLayout());
        MonsterSurvey.getContentPane().add(jPanel35, java.awt.BorderLayout.CENTER);

        MonsterTagsWindow.setResizable(false);
        MonsterTagsWindow.setSize(new java.awt.Dimension(300, 300));

        mTagWindow_GridBox.setLayout(new java.awt.GridLayout(12, 2));

        mTagWindow_MonsterTagsTitle.setText("Monster Tags:");
        mTagWindow_GridBox.add(mTagWindow_MonsterTagsTitle);

        mTagWindow_OrgTagsTitle.setText("Organization Tags:");
        mTagWindow_GridBox.add(mTagWindow_OrgTagsTitle);

        mTagWindow_Magical.setText("Magical");
        mTagWindow_Magical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTagWindow_MagicalActionPerformed(evt);
            }
        });
        mTagWindow_GridBox.add(mTagWindow_Magical);

        OrganizationTagsGroup.add(mTagWindow_Horde);
        mTagWindow_Horde.setText("Horde");
        mTagWindow_GridBox.add(mTagWindow_Horde);

        mTagWindow_Devious.setText("Devious");
        mTagWindow_GridBox.add(mTagWindow_Devious);

        OrganizationTagsGroup.add(mTagWindow_Group);
        mTagWindow_Group.setText("Group");
        mTagWindow_Group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTagWindow_GroupActionPerformed(evt);
            }
        });
        mTagWindow_GridBox.add(mTagWindow_Group);

        mTagWindow_Amorphous.setText("Amorphous");
        mTagWindow_GridBox.add(mTagWindow_Amorphous);

        OrganizationTagsGroup.add(mTagWindow_Solitary);
        mTagWindow_Solitary.setText("Solitary");
        mTagWindow_GridBox.add(mTagWindow_Solitary);

        mTagWindow_Organized.setText("Organized");
        mTagWindow_GridBox.add(mTagWindow_Organized);
        mTagWindow_GridBox.add(filler1);

        mTagWindow_Intelligent.setText("Intelligent");
        mTagWindow_GridBox.add(mTagWindow_Intelligent);

        mTagWindow_SizeTagsTitle.setText("Size Tags:");
        mTagWindow_GridBox.add(mTagWindow_SizeTagsTitle);

        mTagWindow_Hoarder.setText("Hoarder");
        mTagWindow_GridBox.add(mTagWindow_Hoarder);

        SizeTagsGroup.add(mTagWindow_Tiny);
        mTagWindow_Tiny.setText("Tiny");
        mTagWindow_GridBox.add(mTagWindow_Tiny);

        mTagWindow_Stealthy.setText("Stealthy");
        mTagWindow_GridBox.add(mTagWindow_Stealthy);

        SizeTagsGroup.add(mTagWindow_Small);
        mTagWindow_Small.setText("Small");
        mTagWindow_GridBox.add(mTagWindow_Small);

        mTagWindow_Terrifying.setText("Terrifying");
        mTagWindow_GridBox.add(mTagWindow_Terrifying);

        SizeTagsGroup.add(mTagWindow_Normal);
        mTagWindow_Normal.setText("Normal");
        mTagWindow_GridBox.add(mTagWindow_Normal);

        mTagWindow_Cautious.setText("Cautious");
        mTagWindow_GridBox.add(mTagWindow_Cautious);

        SizeTagsGroup.add(mTagWindow_Large);
        mTagWindow_Large.setText("Large");
        mTagWindow_GridBox.add(mTagWindow_Large);

        mTagWindow_Construct.setText("Construct");
        mTagWindow_GridBox.add(mTagWindow_Construct);

        SizeTagsGroup.add(mTagWindow_Huge);
        mTagWindow_Huge.setText("Huge");
        mTagWindow_GridBox.add(mTagWindow_Huge);

        mTagWindow_Planar.setText("Planar");
        mTagWindow_GridBox.add(mTagWindow_Planar);

        MonsterTagsWindow.getContentPane().add(mTagWindow_GridBox, java.awt.BorderLayout.CENTER);

        mTagWindow_ButtonBox.setLayout(new java.awt.BorderLayout());

        mTagWindow_cancelButton.setText("Cancel");
        mTagWindow_ButtonBox.add(mTagWindow_cancelButton, java.awt.BorderLayout.WEST);

        mTagWindow_saveButton.setText("Save");
        mTagWindow_ButtonBox.add(mTagWindow_saveButton, java.awt.BorderLayout.EAST);

        MonsterTagsWindow.getContentPane().add(mTagWindow_ButtonBox, java.awt.BorderLayout.SOUTH);

        AttackTagsWindow.setResizable(false);
        AttackTagsWindow.setSize(new java.awt.Dimension(300, 275));

        aTagsWindow_Title.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        aTagsWindow_Title.setText(" Attack Tags:");
        AttackTagsWindow.getContentPane().add(aTagsWindow_Title, java.awt.BorderLayout.NORTH);

        aTagsWindow_GridBox.setLayout(new java.awt.GridLayout(7, 2));

        aTagsWindow_AmmoBox.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
        aTagsWindow_AmmoBox.add(aTagsWindow_AmmoCheck);

        aTagsWindow_AmmoSpin.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        aTagsWindow_AmmoBox.add(aTagsWindow_AmmoSpin);

        aTagsWindow_AmmoLabel.setText(" Ammo");
        aTagsWindow_AmmoBox.add(aTagsWindow_AmmoLabel);

        aTagsWindow_GridBox.add(aTagsWindow_AmmoBox);

        aTagsWindow_StunCheck.setText("Stun");
        aTagsWindow_GridBox.add(aTagsWindow_StunCheck);

        aTagsWindow_ForcefulCheck.setText("Forceful");
        aTagsWindow_ForcefulCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTagsWindow_ForcefulCheckActionPerformed(evt);
            }
        });
        aTagsWindow_GridBox.add(aTagsWindow_ForcefulCheck);

        aTagsWindow_ThrownCheck.setText("Thrown");
        aTagsWindow_ThrownCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTagsWindow_ThrownCheckActionPerformed(evt);
            }
        });
        aTagsWindow_GridBox.add(aTagsWindow_ThrownCheck);

        aTagsWindow_IgnoresArmorCheck.setText("Ignores Armor");
        aTagsWindow_GridBox.add(aTagsWindow_IgnoresArmorCheck);

        aTagsWindow_HandCheck.setText("Hand");
        aTagsWindow_GridBox.add(aTagsWindow_HandCheck);

        aTagsWindow_MessyCheck.setText("Messy");
        aTagsWindow_GridBox.add(aTagsWindow_MessyCheck);

        aTagsWindow_CloseCheck.setText("Close");
        aTagsWindow_GridBox.add(aTagsWindow_CloseCheck);

        aTagsWindow_PiercingBox.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 2));
        aTagsWindow_PiercingBox.add(aTagsWindow_PiercingCheck);

        aTagsWindow_PiercingSpin.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        aTagsWindow_PiercingBox.add(aTagsWindow_PiercingSpin);

        aTagsWindow_PiercingLabel.setText(" Piercing");
        aTagsWindow_PiercingBox.add(aTagsWindow_PiercingLabel);

        aTagsWindow_GridBox.add(aTagsWindow_PiercingBox);

        aTagsWindow_ReachCheck.setText("Reach");
        aTagsWindow_GridBox.add(aTagsWindow_ReachCheck);

        aTagsWindow_PreciseCheck.setText("Precise");
        aTagsWindow_PreciseCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTagsWindow_PreciseCheckActionPerformed(evt);
            }
        });
        aTagsWindow_GridBox.add(aTagsWindow_PreciseCheck);

        aTagsWindow_NearCheck.setText("Near");
        aTagsWindow_GridBox.add(aTagsWindow_NearCheck);

        aTagsWindow_ReloadCheck.setText("Reload");
        aTagsWindow_GridBox.add(aTagsWindow_ReloadCheck);

        aTagsWindow_FarCheck.setText("Far");
        aTagsWindow_GridBox.add(aTagsWindow_FarCheck);

        AttackTagsWindow.getContentPane().add(aTagsWindow_GridBox, java.awt.BorderLayout.CENTER);

        aTagsWindow_ButtonBox.setLayout(new java.awt.BorderLayout());

        aTagsWindow_CancelButton.setText("Cancel");
        aTagsWindow_ButtonBox.add(aTagsWindow_CancelButton, java.awt.BorderLayout.WEST);

        aTagsWindow_SaveButton.setText("Save");
        aTagsWindow_ButtonBox.add(aTagsWindow_SaveButton, java.awt.BorderLayout.EAST);

        AttackTagsWindow.getContentPane().add(aTagsWindow_ButtonBox, java.awt.BorderLayout.PAGE_END);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 786));

        ControlBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ControlBar.setMaximumSize(new java.awt.Dimension(1024, 125));
        ControlBar.setPreferredSize(new java.awt.Dimension(1024, 125));
        ControlBar.setLayout(new java.awt.GridLayout(1, 2));

        controlbar_MainLabel.setFont(new java.awt.Font("Lucida Blackletter", 1, 75)); // NOI18N
        controlbar_MainLabel.setText("  The Bestiary");
        ControlBar.add(controlbar_MainLabel);

        ModeButtons.setLayout(new java.awt.GridLayout(1, 0));
        ModeButtons.add(headerFiller);

        ModeToggle.add(controlbar_MyBestiaryButton);
        controlbar_MyBestiaryButton.setFont(new java.awt.Font("Lucida Blackletter", 0, 18)); // NOI18N
        controlbar_MyBestiaryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2013-11-02 15.26.05 copy.jpg"))); // NOI18N
        controlbar_MyBestiaryButton.setText("My Bestiary");
        controlbar_MyBestiaryButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        controlbar_MyBestiaryButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ModeButtons.add(controlbar_MyBestiaryButton);

        ModeToggle.add(controlbar_NewMonsterButton);
        controlbar_NewMonsterButton.setFont(new java.awt.Font("Lucida Blackletter", 0, 18)); // NOI18N
        controlbar_NewMonsterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2013-11-02 15.26.12.jpg"))); // NOI18N
        controlbar_NewMonsterButton.setText("New Monster");
        controlbar_NewMonsterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        controlbar_NewMonsterButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ModeButtons.add(controlbar_NewMonsterButton);

        ModeToggle.add(controlbar_CodexButton);
        controlbar_CodexButton.setFont(new java.awt.Font("Lucida Blackletter", 0, 18)); // NOI18N
        controlbar_CodexButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2013-11-02 15.26.12 copy.jpg"))); // NOI18N
        controlbar_CodexButton.setText("Codex");
        controlbar_CodexButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        controlbar_CodexButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ModeButtons.add(controlbar_CodexButton);

        ControlBar.add(ModeButtons);

        getContentPane().add(ControlBar, java.awt.BorderLayout.NORTH);

        ModeScreens.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ModeScreens.setMinimumSize(new java.awt.Dimension(16, 661));
        ModeScreens.setPreferredSize(new java.awt.Dimension(1024, 661));
        ModeScreens.setLayout(new java.awt.CardLayout());

        BestiaryPage.setLayout(new java.awt.BorderLayout());

        bestiarypage_left.setMinimumSize(new java.awt.Dimension(780, 23));
        bestiarypage_left.setPreferredSize(new java.awt.Dimension(700, 100));
        bestiarypage_left.setSize(new java.awt.Dimension(760, 100));
        bestiarypage_left.setLayout(new java.awt.BorderLayout());

        bestiarypage_mainscroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        bestiarypage_mainscroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        bestiarypage_mainscroll.setMinimumSize(new java.awt.Dimension(760, 23));
        bestiarypage_mainscroll.setPreferredSize(new java.awt.Dimension(700, 100));

        bestiarypage_mainScrollPane.setSize(new java.awt.Dimension(760, 0));
        bestiarypage_mainScrollPane.setLayout(new java.awt.GridLayout(5, 0, 0, 20));
        bestiarypage_mainScrollPane.add(bestiarypage_card1);
        bestiarypage_mainScrollPane.add(bestiarypage_card2);
        bestiarypage_mainScrollPane.add(bestiarypage_card3);
        bestiarypage_mainScrollPane.add(bestiarypage_card4);
        bestiarypage_mainScrollPane.add(bestiarypage_card5);

        bestiarypage_mainscroll.setViewportView(bestiarypage_mainScrollPane);

        bestiarypage_left.add(bestiarypage_mainscroll, java.awt.BorderLayout.WEST);

        BestiaryPage.add(bestiarypage_left, java.awt.BorderLayout.WEST);

        bestiarypage_right.setLayout(new java.awt.BorderLayout());

        bestiarypage_tagBoxes.setLayout(new java.awt.GridLayout(2, 0));

        bestiarypage_collectionTagsPane.setLayout(new java.awt.BorderLayout());

        bestiarypage_CollectionsLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        bestiarypage_CollectionsLabel.setText(" Collections:");
        bestiarypage_CollectionsLabel.setPreferredSize(new java.awt.Dimension(101, 30));
        bestiarypage_collectionTagsPane.add(bestiarypage_CollectionsLabel, java.awt.BorderLayout.PAGE_START);
        bestiarypage_collectionTagsPane.add(bestiarypage_filler1, java.awt.BorderLayout.LINE_START);
        bestiarypage_collectionTagsPane.add(bestiarypage_filler2, java.awt.BorderLayout.LINE_END);

        bestiarypage_collectionsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        bestiarypage_CollectionsPane.setLayout(new java.awt.BorderLayout());

        bestiarypage_collectionsGridBox.setLayout(new java.awt.GridLayout(10, 0));

        bestiarypage_dummyCheck.setText("Starred");
        bestiarypage_dummyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestiarypage_dummyCheckActionPerformed(evt);
            }
        });
        bestiarypage_collectionsGridBox.add(bestiarypage_dummyCheck);

        bestiarypage_dummyCheck2.setText("Cats");
        bestiarypage_collectionsGridBox.add(bestiarypage_dummyCheck2);

        bestiarypage_CollectionsPane.add(bestiarypage_collectionsGridBox, java.awt.BorderLayout.CENTER);
        bestiarypage_CollectionsPane.add(bestiarypage_filler3, java.awt.BorderLayout.WEST);

        bestiarypage_collectionsScrollPane.setViewportView(bestiarypage_CollectionsPane);

        bestiarypage_collectionTagsPane.add(bestiarypage_collectionsScrollPane, java.awt.BorderLayout.CENTER);

        bestiarypage_collectionsButtonBox.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        bestiarypage_collectionsClearSelectionButton.setText("Clear Selections");
        bestiarypage_collectionsButtonBox.add(bestiarypage_collectionsClearSelectionButton);

        bestiarypage_collectionTagsPane.add(bestiarypage_collectionsButtonBox, java.awt.BorderLayout.SOUTH);

        bestiarypage_tagBoxes.add(bestiarypage_collectionTagsPane);

        bestiarypage_monsterTagsPane.setLayout(new java.awt.BorderLayout());

        bestiarypage_monsterTagsTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        bestiarypage_monsterTagsTitle.setText(" Monster Types:");
        bestiarypage_monsterTagsTitle.setPreferredSize(new java.awt.Dimension(73, 30));
        bestiarypage_monsterTagsPane.add(bestiarypage_monsterTagsTitle, java.awt.BorderLayout.PAGE_START);
        bestiarypage_monsterTagsPane.add(bestiarypage_filler4, java.awt.BorderLayout.LINE_END);
        bestiarypage_monsterTagsPane.add(bestiarypage_filler5, java.awt.BorderLayout.LINE_START);

        bestiarypage_monsterTagsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        bestiarypage_monsterTagPaneMid.setLayout(new java.awt.BorderLayout());
        bestiarypage_monsterTagPaneMid.add(bestiarypage_filler6, java.awt.BorderLayout.WEST);

        bestiarypage_monsterTagsGridBox.setLayout(new java.awt.GridLayout(22, 0));

        bestiarypage_monsterTagsMonsterLabel.setText("Monster");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_monsterTagsMonsterLabel);

        bestiarypage_tag_Magical.setText("Magical");
        bestiarypage_tag_Magical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestiarypage_tag_MagicalActionPerformed(evt);
            }
        });
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Magical);

        bestiarypage_tag__Devious.setText("Devious");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag__Devious);

        bestiarypage_tag_Amorphous.setText("Amorphous");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Amorphous);

        bestiarypage_tag_Organized.setText("Organized");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Organized);

        bestiarypage_tag_Intelligent.setText("Intelligent");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Intelligent);

        bestiarypage_tag_Hoarder.setText("Hoarder");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Hoarder);

        bestiarypage_tag_Stealthy.setText("Stealthy");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Stealthy);

        bestiarypage_tag_Terrifying.setText("Terrifying");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Terrifying);

        bestiarypage_tag_Cautious.setText("Cautious");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Cautious);

        bestiarypage_tag_Construct.setText("Construct");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Construct);

        bestiarypage_tag_Planar.setText("Planar");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Planar);

        bestiarypage_monsterTagsOrgLabel.setText("Organization");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_monsterTagsOrgLabel);

        myBestiaryOrgTags.add(bestiarypage_tag_Horde);
        bestiarypage_tag_Horde.setText("Horde");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Horde);

        myBestiaryOrgTags.add(bestiarypage_tag_Group);
        bestiarypage_tag_Group.setText("Group");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Group);

        myBestiaryOrgTags.add(bestiarypage_tag_Solitary);
        bestiarypage_tag_Solitary.setText("Solitary");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Solitary);

        bestiarypage_monsterTagsSizeLabel.setText("Size");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_monsterTagsSizeLabel);

        myBestiarySizeTags.add(bestiarypage_tag_Tiny);
        bestiarypage_tag_Tiny.setText("Tiny");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Tiny);

        myBestiarySizeTags.add(bestiarypage_tag_Small);
        bestiarypage_tag_Small.setText("Small");
        bestiarypage_tag_Small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestiarypage_tag_SmallActionPerformed(evt);
            }
        });
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Small);

        myBestiarySizeTags.add(bestiarypage_tag_Normal);
        bestiarypage_tag_Normal.setText("Normal");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Normal);

        myBestiarySizeTags.add(bestiarypage_tag_Large);
        bestiarypage_tag_Large.setText("Large");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Large);

        myBestiarySizeTags.add(bestiarypage_tag_Huge);
        bestiarypage_tag_Huge.setText("Huge");
        bestiarypage_monsterTagsGridBox.add(bestiarypage_tag_Huge);

        bestiarypage_monsterTagPaneMid.add(bestiarypage_monsterTagsGridBox, java.awt.BorderLayout.CENTER);

        bestiarypage_monsterTagsScrollPane.setViewportView(bestiarypage_monsterTagPaneMid);

        bestiarypage_monsterTagsPane.add(bestiarypage_monsterTagsScrollPane, java.awt.BorderLayout.CENTER);

        bestiarypage_monsterTagButtonBox.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        bestiarypage_monsterTagClearSelectionsButton.setText("Clear Selections");
        bestiarypage_monsterTagButtonBox.add(bestiarypage_monsterTagClearSelectionsButton);

        bestiarypage_monsterTagsPane.add(bestiarypage_monsterTagButtonBox, java.awt.BorderLayout.SOUTH);

        bestiarypage_tagBoxes.add(bestiarypage_monsterTagsPane);

        bestiarypage_right.add(bestiarypage_tagBoxes, java.awt.BorderLayout.CENTER);

        bestiarypage_filterButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        bestiarypage_filterButton.setText("Filter");
        bestiarypage_filterPane.add(bestiarypage_filterButton);

        bestiarypage_right.add(bestiarypage_filterPane, java.awt.BorderLayout.NORTH);

        BestiaryPage.add(bestiarypage_right, java.awt.BorderLayout.CENTER);

        ModeScreens.add(BestiaryPage, "card2");

        MonsterFocus.setLayout(new java.awt.BorderLayout());

        monsterFocus_Sidebar.setLayout(new java.awt.BorderLayout());

        monsterFocus_UploadBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        monsterFocus_UploadBox.setLayout(new java.awt.BorderLayout());

        monsterFocus_UploadButton.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        monsterFocus_UploadButton.setText("Upload To Codex");
        monsterFocus_UploadButton.setActionCommand("<html>Upload To <br> Codex</html>");
        monsterFocus_UploadButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        monsterFocus_UploadBox.add(monsterFocus_UploadButton, java.awt.BorderLayout.CENTER);
        monsterFocus_UploadBox.add(monsterFocus_filler1, java.awt.BorderLayout.PAGE_START);
        monsterFocus_UploadBox.add(monsterFocus_filler2, java.awt.BorderLayout.PAGE_END);
        monsterFocus_UploadBox.add(monsterFocus_filler3, java.awt.BorderLayout.LINE_END);
        monsterFocus_UploadBox.add(monsterFocus_filler4, java.awt.BorderLayout.LINE_START);

        monsterFocus_Sidebar.add(monsterFocus_UploadBox, java.awt.BorderLayout.NORTH);

        monsterFocus_currentCollectionsPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        monsterFocus_currentCollectionsPane.setLayout(new java.awt.BorderLayout());

        monsterFocus_currentCollectionsTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        monsterFocus_currentCollectionsTitle.setText("Current Collections:");
        monsterFocus_currentCollectionsTitle.setPreferredSize(new java.awt.Dimension(172, 30));
        monsterFocus_currentCollectionsPane.add(monsterFocus_currentCollectionsTitle, java.awt.BorderLayout.PAGE_START);

        monsterFocus_currentCollectionsEditPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        monsterFocus_currentCollectionsEditButton.setText("Edit Collections");
        monsterFocus_currentCollectionsEditPane.add(monsterFocus_currentCollectionsEditButton);

        monsterFocus_currentCollectionsPane.add(monsterFocus_currentCollectionsEditPane, java.awt.BorderLayout.PAGE_END);

        monsterFocus_currentCollectionsList.setBackground(new java.awt.Color(238, 238, 238));
        monsterFocus_currentCollectionsList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        monsterFocus_currentCollectionsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Orc", "Plains" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        monsterFocus_currentCollectionsScrollPane.setViewportView(monsterFocus_currentCollectionsList);

        monsterFocus_currentCollectionsPane.add(monsterFocus_currentCollectionsScrollPane, java.awt.BorderLayout.CENTER);
        monsterFocus_currentCollectionsPane.add(monsterFocus_filler6, java.awt.BorderLayout.LINE_END);
        monsterFocus_currentCollectionsPane.add(monsterFocus_filler8, java.awt.BorderLayout.LINE_START);

        monsterFocus_Sidebar.add(monsterFocus_currentCollectionsPane, java.awt.BorderLayout.CENTER);

        MonsterFocus.add(monsterFocus_Sidebar, java.awt.BorderLayout.LINE_END);

        monsterFocus_GMNotePane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        monsterFocus_GMNotePane.setLayout(new java.awt.BorderLayout());

        monsterFocus_GMNotesTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        monsterFocus_GMNotesTitle.setText("GM Notes:");
        monsterFocus_GMNotesTitle.setPreferredSize(new java.awt.Dimension(91, 30));
        monsterFocus_GMNotePane.add(monsterFocus_GMNotesTitle, java.awt.BorderLayout.NORTH);

        monsterFocus_GMNotesScrollPane.setPreferredSize(new java.awt.Dimension(100, 150));

        monsterFocus_GMNotesTextArea.setEditable(false);
        monsterFocus_GMNotesTextArea.setBackground(new java.awt.Color(238, 238, 238));
        monsterFocus_GMNotesTextArea.setColumns(20);
        monsterFocus_GMNotesTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        monsterFocus_GMNotesTextArea.setRows(5);
        monsterFocus_GMNotesScrollPane.setViewportView(monsterFocus_GMNotesTextArea);

        monsterFocus_GMNotePane.add(monsterFocus_GMNotesScrollPane, java.awt.BorderLayout.CENTER);
        monsterFocus_GMNotePane.add(monsterFocus_filler5, java.awt.BorderLayout.WEST);
        monsterFocus_GMNotePane.add(monsterFocus_filler7, java.awt.BorderLayout.EAST);

        monsterFocus_GMNotesButtonBox.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        monsterFocus_GMNotesEditButton.setText("Edit Note");
        monsterFocus_GMNotesButtonBox.add(monsterFocus_GMNotesEditButton);

        monsterFocus_GMNotePane.add(monsterFocus_GMNotesButtonBox, java.awt.BorderLayout.SOUTH);

        MonsterFocus.add(monsterFocus_GMNotePane, java.awt.BorderLayout.SOUTH);

        monsterFocus_MonsterCard.setdAttackTags("Attack, Tags, Blah");
        monsterFocus_MonsterCard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        MonsterFocus.add(monsterFocus_MonsterCard, java.awt.BorderLayout.CENTER);

        monsterFocus_BackButtonBox.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        monsterFocus_backButton.setText("Back to Bestiary");
        monsterFocus_BackButtonBox.add(monsterFocus_backButton);

        MonsterFocus.add(monsterFocus_BackButtonBox, java.awt.BorderLayout.PAGE_START);

        ModeScreens.add(MonsterFocus, "card3");

        CodexPage.setLayout(new java.awt.BorderLayout());

        CodexPage_MainScrollPanel.setBackground(new java.awt.Color(238, 238, 238));
        CodexPage_MainScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CodexPage_MainScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        CodexPage_MainPanel.setLayout(new java.awt.GridLayout(1, 2));

        CodexPage_PopularMonstersTopPanel.setLayout(new java.awt.BorderLayout());
        CodexPage_PopularMonstersTopPanel.add(CodexPage_filler1, java.awt.BorderLayout.EAST);
        CodexPage_PopularMonstersTopPanel.add(CodexPage_filler2, java.awt.BorderLayout.WEST);

        CodexPage_PopularMonstersCards.setLayout(new java.awt.GridLayout(5, 0, 0, 10));
        CodexPage_PopularMonstersCards.add(CodexPage_PopularCard1);
        CodexPage_PopularMonstersCards.add(CodexPage_PopularCard2);
        CodexPage_PopularMonstersCards.add(CodexPage_PopularCard3);
        CodexPage_PopularMonstersCards.add(CodexPage_PopularCard4);
        CodexPage_PopularMonstersCards.add(CodexPage_PopularCard5);

        CodexPage_PopularMonstersTopPanel.add(CodexPage_PopularMonstersCards, java.awt.BorderLayout.CENTER);

        CodexPage_PopularMonsterTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        CodexPage_PopularMonsterTitle.setText("  Popular Monsters");
        CodexPage_PopularMonsterTitle.setPreferredSize(new java.awt.Dimension(151, 30));
        CodexPage_PopularMonstersTopPanel.add(CodexPage_PopularMonsterTitle, java.awt.BorderLayout.NORTH);

        CodexPage_MainPanel.add(CodexPage_PopularMonstersTopPanel);

        CodexPage_RecentMonstersTopPane.setLayout(new java.awt.BorderLayout());
        CodexPage_RecentMonstersTopPane.add(CodexPage_filler3, java.awt.BorderLayout.WEST);
        CodexPage_RecentMonstersTopPane.add(CodexPage_filler4, java.awt.BorderLayout.EAST);

        CodexPage_RecentMonstersCards.setLayout(new java.awt.GridLayout(5, 0, 0, 10));
        CodexPage_RecentMonstersCards.add(CodexPage_RecentCard1);
        CodexPage_RecentMonstersCards.add(CodexPage_RecentCard2);
        CodexPage_RecentMonstersCards.add(CodexPage_RecentCard3);
        CodexPage_RecentMonstersCards.add(CodexPage_RecentCard4);
        CodexPage_RecentMonstersCards.add(CodexPage_RecentCard5);

        CodexPage_RecentMonstersTopPane.add(CodexPage_RecentMonstersCards, java.awt.BorderLayout.CENTER);

        CodexPage_RecentMonstersTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        CodexPage_RecentMonstersTitle.setText("Recent Monsters");
        CodexPage_RecentMonstersTitle.setPreferredSize(new java.awt.Dimension(144, 30));
        CodexPage_RecentMonstersTopPane.add(CodexPage_RecentMonstersTitle, java.awt.BorderLayout.PAGE_START);

        CodexPage_MainPanel.add(CodexPage_RecentMonstersTopPane);

        CodexPage_MainScrollPanel.setViewportView(CodexPage_MainPanel);

        CodexPage.add(CodexPage_MainScrollPanel, java.awt.BorderLayout.CENTER);

        ModeScreens.add(CodexPage, "card4");

        getContentPane().add(ModeScreens, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MonsterEdit_NewMoveFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonsterEdit_NewMoveFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonsterEdit_NewMoveFieldActionPerformed

    private void MonsterEdit_NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonsterEdit_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonsterEdit_NameFieldActionPerformed

    private void MonsterEdit_AttackNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonsterEdit_AttackNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonsterEdit_AttackNameFieldActionPerformed

    private void aTagsWindow_ThrownCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTagsWindow_ThrownCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTagsWindow_ThrownCheckActionPerformed

    private void aTagsWindow_ForcefulCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTagsWindow_ForcefulCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTagsWindow_ForcefulCheckActionPerformed

    private void aTagsWindow_PreciseCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTagsWindow_PreciseCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTagsWindow_PreciseCheckActionPerformed

    private void mTagWindow_MagicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTagWindow_MagicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTagWindow_MagicalActionPerformed

    private void mTagWindow_GroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTagWindow_GroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTagWindow_GroupActionPerformed

    private void bestiarypage_tag_MagicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestiarypage_tag_MagicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestiarypage_tag_MagicalActionPerformed

    private void bestiarypage_tag_SmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestiarypage_tag_SmallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestiarypage_tag_SmallActionPerformed

    private void bestiarypage_dummyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestiarypage_dummyCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestiarypage_dummyCheckActionPerformed
    
    private void jBtnSurveyBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSurveyBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSurveyBackActionPerformed

    private void jBtnSurveyNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSurveyNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSurveyNextActionPerformed

    private void jBtnSurveyBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSurveyBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSurveyBackActionPerformed

    private void jBtnSurveyNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSurveyNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSurveyNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BestiaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BestiaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BestiaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BestiaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BestiaryGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AttackTagsWindow;
    private javax.swing.JPanel BestiaryPage;
    private javax.swing.JPanel CodexPage;
    private javax.swing.JPanel CodexPage_MainPanel;
    private javax.swing.JScrollPane CodexPage_MainScrollPanel;
    private MiniMonsterCard CodexPage_PopularCard1;
    private MiniMonsterCard CodexPage_PopularCard2;
    private MiniMonsterCard CodexPage_PopularCard3;
    private MiniMonsterCard CodexPage_PopularCard4;
    private MiniMonsterCard CodexPage_PopularCard5;
    private javax.swing.JLabel CodexPage_PopularMonsterTitle;
    private javax.swing.JPanel CodexPage_PopularMonstersCards;
    private javax.swing.JPanel CodexPage_PopularMonstersTopPanel;
    private MiniMonsterCard CodexPage_RecentCard1;
    private MiniMonsterCard CodexPage_RecentCard2;
    private MiniMonsterCard CodexPage_RecentCard3;
    private MiniMonsterCard CodexPage_RecentCard4;
    private MiniMonsterCard CodexPage_RecentCard5;
    private javax.swing.JPanel CodexPage_RecentMonstersCards;
    private javax.swing.JLabel CodexPage_RecentMonstersTitle;
    private javax.swing.JPanel CodexPage_RecentMonstersTopPane;
    private javax.swing.Box.Filler CodexPage_filler1;
    private javax.swing.Box.Filler CodexPage_filler2;
    private javax.swing.Box.Filler CodexPage_filler3;
    private javax.swing.Box.Filler CodexPage_filler4;
    private javax.swing.JPanel ControlBar;
    private javax.swing.JPanel ModeButtons;
    private javax.swing.JPanel ModeScreens;
    private javax.swing.ButtonGroup ModeToggle;
    private javax.swing.JDialog MonsterEdit;
    private javax.swing.JButton MonsterEdit_AddMoveButton;
    private javax.swing.JLabel MonsterEdit_ArmorLabel;
    private javax.swing.JSpinner MonsterEdit_ArmorValue;
    private javax.swing.JSpinner MonsterEdit_AttackMod;
    private javax.swing.JTextField MonsterEdit_AttackNameField;
    private javax.swing.JLabel MonsterEdit_AttackNameLabel;
    private javax.swing.JButton MonsterEdit_AttackTags;
    private javax.swing.JButton MonsterEdit_CancelButton;
    private javax.swing.JPanel MonsterEdit_Description;
    private javax.swing.JLabel MonsterEdit_DescriptionLabel;
    private javax.swing.JTextArea MonsterEdit_DescriptionPane;
    private javax.swing.JScrollPane MonsterEdit_DescriptionScrollPane;
    private javax.swing.JComboBox MonsterEdit_Dice;
    private javax.swing.JPanel MonsterEdit_EndPane;
    private javax.swing.JLabel MonsterEdit_HPLabel;
    private javax.swing.JSpinner MonsterEdit_HPValue;
    private javax.swing.JPanel MonsterEdit_HeaderInfo;
    private javax.swing.JPanel MonsterEdit_InstinctBox;
    private javax.swing.JTextField MonsterEdit_InstinctField;
    private javax.swing.JLabel MonsterEdit_InstinctLabel;
    private javax.swing.JButton MonsterEdit_MonsterTagsButton;
    private javax.swing.JPanel MonsterEdit_Moves;
    private javax.swing.JPanel MonsterEdit_MovesControlsBox;
    private javax.swing.JLabel MonsterEdit_MovesLabel;
    private javax.swing.JList MonsterEdit_MovesList;
    private javax.swing.JScrollPane MonsterEdit_MovesScrollPane;
    private javax.swing.JTextField MonsterEdit_NameField;
    private javax.swing.JPanel MonsterEdit_NamePanel;
    private javax.swing.JLabel MonsterEdit_NameTitle;
    private javax.swing.JTextField MonsterEdit_NewMoveField;
    private javax.swing.JButton MonsterEdit_RemoveButton;
    private javax.swing.JComboBox MonsterEdit_Rolls;
    private javax.swing.JPanel MonsterEdit_Row1;
    private javax.swing.JPanel MonsterEdit_Row2;
    private javax.swing.JPanel MonsterEdit_Row3;
    private javax.swing.JPanel MonsterEdit_Row4;
    private javax.swing.JButton MonsterEdit_SaveButton;
    private javax.swing.JTextField MonsterEdit_SpecialQualitiesField;
    private javax.swing.JLabel MonsterEdit_SpecialQualitiesLabel;
    private javax.swing.JPanel MonsterEdit_TopPane;
    private javax.swing.Box.Filler MonsterEdit_filler1;
    private javax.swing.Box.Filler MonsterEdit_filler2;
    private javax.swing.Box.Filler MonsterEdit_filler3;
    private javax.swing.Box.Filler MonsterEdit_filler4;
    private javax.swing.Box.Filler MonsterEdit_filler5;
    private javax.swing.Box.Filler MonsterEdit_filler6;
    private javax.swing.Box.Filler MonsterEdit_filler7;
    private javax.swing.Box.Filler MonsterEdit_filler8;
    private javax.swing.JPanel MonsterFocus;
    private javax.swing.JDialog MonsterSurvey;
    private javax.swing.JDialog MonsterTagsWindow;
    private javax.swing.ButtonGroup OrganizationTagsGroup;
    private javax.swing.ButtonGroup SizeTagsGroup;
    private javax.swing.JPanel aTagsWindow_AmmoBox;
    private javax.swing.JCheckBox aTagsWindow_AmmoCheck;
    private javax.swing.JLabel aTagsWindow_AmmoLabel;
    private javax.swing.JSpinner aTagsWindow_AmmoSpin;
    private javax.swing.JPanel aTagsWindow_ButtonBox;
    private javax.swing.JButton aTagsWindow_CancelButton;
    private javax.swing.JCheckBox aTagsWindow_CloseCheck;
    private javax.swing.JCheckBox aTagsWindow_FarCheck;
    private javax.swing.JCheckBox aTagsWindow_ForcefulCheck;
    private javax.swing.JPanel aTagsWindow_GridBox;
    private javax.swing.JCheckBox aTagsWindow_HandCheck;
    private javax.swing.JCheckBox aTagsWindow_IgnoresArmorCheck;
    private javax.swing.JCheckBox aTagsWindow_MessyCheck;
    private javax.swing.JCheckBox aTagsWindow_NearCheck;
    private javax.swing.JPanel aTagsWindow_PiercingBox;
    private javax.swing.JCheckBox aTagsWindow_PiercingCheck;
    private javax.swing.JLabel aTagsWindow_PiercingLabel;
    private javax.swing.JSpinner aTagsWindow_PiercingSpin;
    private javax.swing.JCheckBox aTagsWindow_PreciseCheck;
    private javax.swing.JCheckBox aTagsWindow_ReachCheck;
    private javax.swing.JCheckBox aTagsWindow_ReloadCheck;
    private javax.swing.JButton aTagsWindow_SaveButton;
    private javax.swing.JCheckBox aTagsWindow_StunCheck;
    private javax.swing.JCheckBox aTagsWindow_ThrownCheck;
    private javax.swing.JLabel aTagsWindow_Title;
    private javax.swing.JLabel bestiarypage_CollectionsLabel;
    private javax.swing.JPanel bestiarypage_CollectionsPane;
    private LargeMonsterCard bestiarypage_card1;
    private LargeMonsterCard bestiarypage_card2;
    private LargeMonsterCard bestiarypage_card3;
    private LargeMonsterCard bestiarypage_card4;
    private LargeMonsterCard bestiarypage_card5;
    private javax.swing.JPanel bestiarypage_collectionTagsPane;
    private javax.swing.JPanel bestiarypage_collectionsButtonBox;
    private javax.swing.JButton bestiarypage_collectionsClearSelectionButton;
    private javax.swing.JPanel bestiarypage_collectionsGridBox;
    private javax.swing.JScrollPane bestiarypage_collectionsScrollPane;
    private javax.swing.JCheckBox bestiarypage_dummyCheck;
    private javax.swing.JCheckBox bestiarypage_dummyCheck2;
    private javax.swing.Box.Filler bestiarypage_filler1;
    private javax.swing.Box.Filler bestiarypage_filler2;
    private javax.swing.Box.Filler bestiarypage_filler3;
    private javax.swing.Box.Filler bestiarypage_filler4;
    private javax.swing.Box.Filler bestiarypage_filler5;
    private javax.swing.Box.Filler bestiarypage_filler6;
    private javax.swing.JButton bestiarypage_filterButton;
    private javax.swing.JPanel bestiarypage_filterPane;
    private javax.swing.JPanel bestiarypage_left;
    private javax.swing.JPanel bestiarypage_mainScrollPane;
    private javax.swing.JScrollPane bestiarypage_mainscroll;
    private javax.swing.JPanel bestiarypage_monsterTagButtonBox;
    private javax.swing.JButton bestiarypage_monsterTagClearSelectionsButton;
    private javax.swing.JPanel bestiarypage_monsterTagPaneMid;
    private javax.swing.JPanel bestiarypage_monsterTagsGridBox;
    private javax.swing.JLabel bestiarypage_monsterTagsMonsterLabel;
    private javax.swing.JLabel bestiarypage_monsterTagsOrgLabel;
    private javax.swing.JPanel bestiarypage_monsterTagsPane;
    private javax.swing.JScrollPane bestiarypage_monsterTagsScrollPane;
    private javax.swing.JLabel bestiarypage_monsterTagsSizeLabel;
    private javax.swing.JLabel bestiarypage_monsterTagsTitle;
    private javax.swing.JPanel bestiarypage_right;
    private javax.swing.JPanel bestiarypage_tagBoxes;
    private javax.swing.JCheckBox bestiarypage_tag_Amorphous;
    private javax.swing.JCheckBox bestiarypage_tag_Cautious;
    private javax.swing.JCheckBox bestiarypage_tag_Construct;
    private javax.swing.JCheckBox bestiarypage_tag_Group;
    private javax.swing.JCheckBox bestiarypage_tag_Hoarder;
    private javax.swing.JCheckBox bestiarypage_tag_Horde;
    private javax.swing.JCheckBox bestiarypage_tag_Huge;
    private javax.swing.JCheckBox bestiarypage_tag_Intelligent;
    private javax.swing.JCheckBox bestiarypage_tag_Large;
    private javax.swing.JCheckBox bestiarypage_tag_Magical;
    private javax.swing.JCheckBox bestiarypage_tag_Normal;
    private javax.swing.JCheckBox bestiarypage_tag_Organized;
    private javax.swing.JCheckBox bestiarypage_tag_Planar;
    private javax.swing.JCheckBox bestiarypage_tag_Small;
    private javax.swing.JCheckBox bestiarypage_tag_Solitary;
    private javax.swing.JCheckBox bestiarypage_tag_Stealthy;
    private javax.swing.JCheckBox bestiarypage_tag_Terrifying;
    private javax.swing.JCheckBox bestiarypage_tag_Tiny;
    private javax.swing.JCheckBox bestiarypage_tag__Devious;
    private javax.swing.JToggleButton controlbar_CodexButton;
    private javax.swing.JLabel controlbar_MainLabel;
    private javax.swing.JToggleButton controlbar_MyBestiaryButton;
    private javax.swing.JToggleButton controlbar_NewMonsterButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler headerFiller;
    private javax.swing.JButton jBtnSurveyBack;
    private javax.swing.JButton jBtnSurveyCancel;
    private javax.swing.JButton jBtnSurveyNext;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox mTagWindow_Amorphous;
    private javax.swing.JPanel mTagWindow_ButtonBox;
    private javax.swing.JCheckBox mTagWindow_Cautious;
    private javax.swing.JCheckBox mTagWindow_Construct;
    private javax.swing.JCheckBox mTagWindow_Devious;
    private javax.swing.JPanel mTagWindow_GridBox;
    private javax.swing.JRadioButton mTagWindow_Group;
    private javax.swing.JCheckBox mTagWindow_Hoarder;
    private javax.swing.JRadioButton mTagWindow_Horde;
    private javax.swing.JRadioButton mTagWindow_Huge;
    private javax.swing.JCheckBox mTagWindow_Intelligent;
    private javax.swing.JRadioButton mTagWindow_Large;
    private javax.swing.JCheckBox mTagWindow_Magical;
    private javax.swing.JLabel mTagWindow_MonsterTagsTitle;
    private javax.swing.JRadioButton mTagWindow_Normal;
    private javax.swing.JLabel mTagWindow_OrgTagsTitle;
    private javax.swing.JCheckBox mTagWindow_Organized;
    private javax.swing.JCheckBox mTagWindow_Planar;
    private javax.swing.JLabel mTagWindow_SizeTagsTitle;
    private javax.swing.JRadioButton mTagWindow_Small;
    private javax.swing.JRadioButton mTagWindow_Solitary;
    private javax.swing.JCheckBox mTagWindow_Stealthy;
    private javax.swing.JCheckBox mTagWindow_Terrifying;
    private javax.swing.JRadioButton mTagWindow_Tiny;
    private javax.swing.JButton mTagWindow_cancelButton;
    private javax.swing.JButton mTagWindow_saveButton;
    private javax.swing.JPanel monsterFocus_BackButtonBox;
    private javax.swing.JPanel monsterFocus_GMNotePane;
    private javax.swing.JPanel monsterFocus_GMNotesButtonBox;
    private javax.swing.JButton monsterFocus_GMNotesEditButton;
    private javax.swing.JScrollPane monsterFocus_GMNotesScrollPane;
    private javax.swing.JTextArea monsterFocus_GMNotesTextArea;
    private javax.swing.JLabel monsterFocus_GMNotesTitle;
    private LargeMonsterCard monsterFocus_MonsterCard;
    private javax.swing.JPanel monsterFocus_Sidebar;
    private javax.swing.JPanel monsterFocus_UploadBox;
    private javax.swing.JButton monsterFocus_UploadButton;
    private javax.swing.JButton monsterFocus_backButton;
    private javax.swing.JButton monsterFocus_currentCollectionsEditButton;
    private javax.swing.JPanel monsterFocus_currentCollectionsEditPane;
    private javax.swing.JList monsterFocus_currentCollectionsList;
    private javax.swing.JPanel monsterFocus_currentCollectionsPane;
    private javax.swing.JScrollPane monsterFocus_currentCollectionsScrollPane;
    private javax.swing.JLabel monsterFocus_currentCollectionsTitle;
    private javax.swing.Box.Filler monsterFocus_filler1;
    private javax.swing.Box.Filler monsterFocus_filler2;
    private javax.swing.Box.Filler monsterFocus_filler3;
    private javax.swing.Box.Filler monsterFocus_filler4;
    private javax.swing.Box.Filler monsterFocus_filler5;
    private javax.swing.Box.Filler monsterFocus_filler6;
    private javax.swing.Box.Filler monsterFocus_filler7;
    private javax.swing.Box.Filler monsterFocus_filler8;
    private javax.swing.ButtonGroup myBestiaryOrgTags;
    private javax.swing.ButtonGroup myBestiarySizeTags;
    // End of variables declaration//GEN-END:variables
}
