/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author martha
 */
public class MonsterPop extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer MonsterPop
     */
    public MonsterPop(Monster monster, BestiaryGUI win, javax.swing.JDialog ownr) {
        mainWin = win;
        mon = monster;
        owner = ownr;
        initComponents();
        mon.loadToCard(this.miniMonsterCard1);
        this.MonsterFocus_GMNotesText.setText(mon.getGMNote());
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    
    public String getMonsterName(){
        return mon.getName();
    }

    public void updateView(){
        mon.loadToCard(this.miniMonsterCard1);
        this.MonsterFocus_GMNotesText.setText(mon.getGMNote());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardPanel = new javax.swing.JPanel();
        MonsterCardPanel = new javax.swing.JPanel();
        miniMonsterCard1 = new MiniMonsterCard();
        GMNotePanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        MonsterFocus_GMNotesTopPane = new javax.swing.JPanel();
        MonsterFocus_GMNotesTitle = new javax.swing.JLabel();
        MonsterFocus_GMNotesScrollPane = new javax.swing.JScrollPane();
        MonsterFocus_GMNotesText = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        ToMonDetails = new javax.swing.JButton();
        FlipButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        CardPanel.setLayout(new java.awt.CardLayout());

        MonsterCardPanel.setLayout(new java.awt.BorderLayout());
        MonsterCardPanel.add(miniMonsterCard1, java.awt.BorderLayout.CENTER);

        CardPanel.add(MonsterCardPanel, "MonsterCard");

        GMNotePanel.setLayout(new java.awt.BorderLayout());
        GMNotePanel.add(filler3, java.awt.BorderLayout.PAGE_START);
        GMNotePanel.add(filler2, java.awt.BorderLayout.EAST);
        GMNotePanel.add(filler1, java.awt.BorderLayout.WEST);

        MonsterFocus_GMNotesTopPane.setLayout(new java.awt.BorderLayout());

        MonsterFocus_GMNotesTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        MonsterFocus_GMNotesTitle.setText("GM Notes:");
        MonsterFocus_GMNotesTitle.setPreferredSize(new java.awt.Dimension(91, 30));
        MonsterFocus_GMNotesTopPane.add(MonsterFocus_GMNotesTitle, java.awt.BorderLayout.PAGE_START);

        MonsterFocus_GMNotesScrollPane.setBackground(new java.awt.Color(238, 238, 238));
        MonsterFocus_GMNotesScrollPane.setPreferredSize(new java.awt.Dimension(100, 150));
        MonsterFocus_GMNotesScrollPane.setSize(new java.awt.Dimension(100, 150));

        MonsterFocus_GMNotesText.setEditable(false);
        MonsterFocus_GMNotesText.setBackground(new java.awt.Color(238, 238, 238));
        MonsterFocus_GMNotesText.setColumns(20);
        MonsterFocus_GMNotesText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        MonsterFocus_GMNotesText.setRows(5);
        MonsterFocus_GMNotesScrollPane.setViewportView(MonsterFocus_GMNotesText);

        MonsterFocus_GMNotesTopPane.add(MonsterFocus_GMNotesScrollPane, java.awt.BorderLayout.CENTER);

        GMNotePanel.add(MonsterFocus_GMNotesTopPane, java.awt.BorderLayout.CENTER);

        CardPanel.add(GMNotePanel, "GMNote");

        add(CardPanel, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        ToMonDetails.setText("Go to Monster Details");
        ToMonDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToMonDetailsActionPerformed(evt);
            }
        });
        jPanel4.add(ToMonDetails, java.awt.BorderLayout.WEST);

        FlipButton.setText("Flip Card");
        FlipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlipButtonActionPerformed(evt);
            }
        });
        jPanel4.add(FlipButton, java.awt.BorderLayout.EAST);

        add(jPanel4, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void ToMonDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToMonDetailsActionPerformed
        
        if(mainWin.BestiaryMonsters.constainsMonster(mon)){
            mainWin.setMainMonster(mon);
        }
        
        owner.dispose();

    }//GEN-LAST:event_ToMonDetailsActionPerformed

    private void FlipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlipButtonActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(this.CardPanel.getLayout());
        cl.next(this.CardPanel);
    }//GEN-LAST:event_FlipButtonActionPerformed

    private Monster mon;
    private BestiaryGUI mainWin;
    private javax.swing.JDialog owner;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardPanel;
    private javax.swing.JButton FlipButton;
    private javax.swing.JPanel GMNotePanel;
    private javax.swing.JPanel MonsterCardPanel;
    private javax.swing.JScrollPane MonsterFocus_GMNotesScrollPane;
    private javax.swing.JTextArea MonsterFocus_GMNotesText;
    private javax.swing.JLabel MonsterFocus_GMNotesTitle;
    private javax.swing.JPanel MonsterFocus_GMNotesTopPane;
    private javax.swing.JButton ToMonDetails;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel jPanel4;
    private MiniMonsterCard miniMonsterCard1;
    // End of variables declaration//GEN-END:variables
}
